version: "3.9"

services:
  mongo:
    image: mongo:6
    container_name: dispensador_mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: dispensador_db
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init:/docker-entrypoint-initdb.d

  backend:
    build: ./backend
    container_name: dispensador_backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    ports:
      - "3000:3000"
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://mongo:27017/dispensador_db
      - MQTT_URL=mqtt://test.mosquitto.org
      - MQTT_TOPIC_EVENTS=dispensador/events
      - MQTT_TOPIC_COMMANDS=dispensador/commands

  frontend:
    build: ./frontend
    container_name: dispensador_frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "5173:80"

networks:
  default:
    name: dispensador_red
